# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-25 15:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colls', '0003_auto_20161025_1614'),
    ]

    operations = [
        migrations.AddField(
            model_name='query',
            name='min_count',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=1),
        ),
        migrations.AlterField(
            model_name='query',
            name='corp',
            field=models.FileField(choices=[('test_XEpypUq.txt', 'test_XEpypUq.txt'), ('test.txt', 'test.txt')], default='None', upload_to=''),
        ),
    ]
