# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-25 16:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colls', '0004_auto_20161025_1844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='query',
            name='min_count',
            field=models.IntegerField(choices=[(2, '2'), (3, '3'), (4, '4'), (5, '5')], default=1),
        ),
    ]
