# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-25 20:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colls', '0005_auto_20161025_1922'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='query',
            name='rang',
        ),
        migrations.AlterField(
            model_name='query',
            name='corp',
            field=models.FileField(choices=[('written.txt', 'written.txt'), ('spoken.txt', 'spoken.txt')], default='None', upload_to=''),
        ),
    ]
